name: Python Syntax Checker Job
on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Checking Python Syntax in code
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
    - name: Adding docker image
      uses: docker://Hello-World@latest
