name: Python Syntax Checker Job
on: push
jobs:
  pythSyntaxCheckerJob:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checking Python Syntax in code
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
